# Generated by Django 3.1.7 on 2021-02-24 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drink',
            old_name='english_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drink',
            name='korean_name',
        ),
        migrations.AlterModelTable(
            name='allergy',
            table=None,
        ),
        migrations.AlterModelTable(
            name='allergydrink',
            table=None,
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
        migrations.AlterModelTable(
            name='drink',
            table=None,
        ),
        migrations.AlterModelTable(
            name='image',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.DeleteModel(
            name='Nutrition',
        ),
    ]
